apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebrc
  namespace: testns
spec:
  replicas: 1
  selector:
    app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: 9182709223/java-web-app-docker:1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: testns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 80
    name: nginx
  - port: 8080
    targetPort: 8080
    name: tomcat
