apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  namespace: testns
  labels:
    app: javawebapp
spec:
  containers:
  - name: javawebapppod
    image: 9182709223/java-web-app:2
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: testns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
